apiVersion: v1
entries:
  rabbitmq-ha:
  - apiVersion: v1
    appVersion: 3.8.7
    created: "2021-01-13T12:09:31.380461224Z"
    description: Highly available RabbitMQ cluster, the open source message broker
      software that implements the Advanced Message Queuing Protocol (AMQP).
    digest: 819e0d13dd5e9bd0930ebad685d3f2ba83d71813c66e424edfc2cb00b35f21cf
    keywords:
    - rabbitmq
    - message queue
    - AMQP
    - AMQPS
    - MQTT
    - STOMP
    name: rabbitmq-ha
    urls:
    - rabbitmq-ha-1.47.1.tgz
    version: 1.47.1
generated: "2021-01-13T12:09:31.375612655Z"
